#!/bin/bash
#set -x

PAGES=../app/pages
CONTENT=content
TEMPLATES=templates

function min_css() {
	echo Minimizing css...

    cat ${CONTENT}/style.css | \
        tr -s ' ' | \
        tr -d '\n' | \
        sed -e 's/ {/{/g' | \
        sed -e 's/{ /{/g' | \
        sed -e 's/; /;/g' | \
        sed -e 's/ ;/;/g' | \
        sed -e 's/ :/;/g' | \
        sed -e 's/ }/}/g' | \
        sed -e 's/, /,/g' | \
        sed -e 's/ ,/,/g'  \
	>${TEMPLATES}/style_min.css
}

function build() {
	TITLE=$(echo $2|cut -d. -f1)
	DEST=${PAGES}/$1
	FOOTER=footer

	[ -d ${DEST} ] || (mkdir -p ${DEST} ; echo "  Making ${DEST}")
	[ -f $1/footer ] && (FOOTER=$1/footer ; echo "  New footer")

	echo "  Page $2  ${DEST}/${TITLE}..."
	jinja2  -D title=${TITLE} 		\
            -D content=${CONTENT}/$1/$2 		\
            -D style=style_min.css 	\
            -D footer=${CONTENT}/$1/${FOOTER} 	\
		page.tmpl> ${DEST}/${TITLE}
}



echo Building page list...
pushd ${CONTENT}
find . -name '*.content' > /tmp/squeal_list
popd


min_css
cd $(dirname $0)/${TEMPLATES}

echo Temporary copy...
cp -r ../${CONTENT} .


echo Building pages...
for f in $(cat /tmp/squeal_list)
do 
	build $(dirname ${f}) $(basename ${f}) 
done
