#!/bin/bash
#set -x

PAGES=../app/pages
CONTENT=content
cd ${CONTENT}

function min_css() {
	echo Minimizing css...

    cat style.css | \
        tr -s ' ' | \
        tr -d '\n' | \
        sed -e 's/ {/{/g' | \
        sed -e 's/{ /{/g' | \
        sed -e 's/; /;/g' | \
        sed -e 's/ ;/;/g' | \
        sed -e 's/ :/;/g' | \
        sed -e 's/ }/}/g' | \
        sed -e 's/, /,/g' | \
        sed -e 's/ ,/,/g'  \
	>style_min.css
}

function build() {
	TITLE=$(echo $2|cut -d. -f1)
	DEST=${PAGES}/$1
	FOOTER=footer

	[ -d ${DEST} ] || (mkdir -p ${DEST} ; echo "  Making ${DEST}")
	[ -f $1/footer ] && (FOOTER=$1/footer ; echo "  New footer ${FOOTER}")

	echo "  Page $2  ${DEST}/${TITLE}..."
	jinja2  -D title=${TITLE} 		\
            -D content=/$1/$2 		\
            -D style=style_min.css 	\
            -D footer=${FOOTER} 	\
		page.tmpl> ${DEST}/${TITLE}
}



echo Building page list...
find . -name '*.content' > /tmp/squeal_list

min_css


echo Building pages...
for f in $(cat /tmp/squeal_list)
do 
	build $(dirname ${f}) $(basename ${f}) 
done
